# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'AnimalHome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimalHome

    # 網路協定
    pod 'Alamofire', '~> 5.5'

    # 下載圖片
    pod 'SDWebImage', '~> 5.0'

    # 靜態檢查codestyle
    pod 'SwiftLint'

    # make Auto Layout easy
    pod 'SnapKit', '~> 5.0.0'


  target 'AnimalHomeTests' do
    inherit! :search_paths
    # Pods for testing
    
   

  end

  target 'AnimalHomeUITests' do
    # Pods for testing
  end

end
